web/project/admin/views.py
from flask import render_template, Blueprint, request, redirect, url_for, flash, abort, jsonify, send_file, Response
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, current_user, login_required, logout_user
from threading import Thread
from itsdangerous import URLSafeTimedSerializer
from datetime import datetime
import os
from .forms import MobileApplicationForm
from project import db, app
from project.models import MobileApplication, User, PsysuiteApplication
from werkzeug.utils import secure_filename
from werkzeug.datastructures import CombinedMultiDict

admin_blueprint = Blueprint('admin', __name__)


################
#### routes ####
################


@admin_blueprint.route('/mobile_application/new', methods=['GET', 'POST'])
@login_required
def mobile_application_new():
    if current_user.role != User.ADMIN:
        return redirect(url_for('user.index'))

    form = MobileApplicationForm(CombinedMultiDict((request.files, request.form)))
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                mobile_application = MobileApplication()
                mobile_application.version = form.version.data
                mobile_application.sver = form.sver.data
                mobile_application.description = form.description.data
                filename = 'allspeak%d.apk' % mobile_application.version
                filepath = os.path.join(app.instance_path, 'mobile_applications', filename)
                mobile_application.apk_path = filepath
                f = form.apk.data
                f.save(filepath)
                db.session.add(mobile_application)
                db.session.commit()
                flash('New mobile application added')
                return redirect(url_for('admin.mobile_application_latest'))
            except IntegrityError:
                db.session.rollback()
                flash('New mobile application added', 'error')
    mobile_application = MobileApplication.query.order_by(MobileApplication.id.desc()).first()
    if mobile_application:
        form.version.data = mobile_application.version + 1
        form.sver.data = mobile_application.sver
    return render_template('mobile_application_new.html', form=form, mobile_application=mobile_application)

@admin_blueprint.route('/mobile_application/latest', methods=['GET'])
@login_required
def mobile_application_latest():
    if current_user.role != User.ADMIN:
        return redirect(url_for('user.index'))

    mobile_application = MobileApplication.query.order_by(MobileApplication.id.desc()).first()
    return render_template('mobile_application_detail.html', mobile_application=mobile_application)

@admin_blueprint.route('/psysuite_application/new', methods=['GET', 'POST'])
@login_required
def psysuite_application_new():
    if current_user.role != User.ADMIN:
        return redirect(url_for('user.index'))

    form = MobileApplicationForm(CombinedMultiDict((request.files, request.form)))
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                mobile_application = PsysuiteApplication()
                mobile_application.version = form.version.data
                mobile_application.sver = form.sver.data
                mobile_application.description = form.description.data
                filename = 'psysuite%d.apk' % mobile_application.version
                filepath = os.path.join(app.instance_path, 'psysuite_applications', filename)
                mobile_application.apk_path = filepath
                f = form.apk.data
                f.save(filepath)
                db.session.add(mobile_application)
                db.session.commit()
                flash('New Psysuite application added')
                return redirect(url_for('admin.psysuite_application_latest'))
            except IntegrityError:
                db.session.rollback()
                flash('New Psysuite application added', 'error')
    mobile_application = PsysuiteApplication.query.order_by(PsysuiteApplication.id.desc()).first()
    if mobile_application:
        form.version.data = mobile_application.version + 1
        form.sver.data = mobile_application.sver
    return render_template('psysuite_application_new.html', form=form, mobile_application=mobile_application)

@admin_blueprint.route('/psysuite_application/latest', methods=['GET'])
@login_required
def psysuite_application_latest():
    if current_user.role != User.ADMIN:
        return redirect(url_for('user.index'))

    mobile_application = PsysuiteApplication.query.order_by(PsysuiteApplication.id.desc()).first()
    return render_template('psysuite_application_detail.html', mobile_application=mobile_application)


@admin_blueprint.route('/admin')
@login_required
def admin():
    if current_user.role != User.ADMIN:
        return redirect(url_for('user.index'))

    return render_template('admin.html')

@admin_blueprint.route('/stableupdate.xml')
def stableupdate():
    mobile_application = MobileApplication.query.order_by(MobileApplication.id.desc()).first()
    if not mobile_application:
        abort(404)

    stableupdate = mobile_application.stableupdate(request.host_url)
    
    return Response(response=stableupdate, status=200, mimetype="application/xml")

@admin_blueprint.route('/allspeak.apk')
def allspeak_apk():
    mobile_application = MobileApplication.query.order_by(MobileApplication.id.desc()).first()
    if not mobile_application:
        abort(404)

    return send_file(mobile_application.apk_path, mimetype='application/vnd.android.package-archive')


@admin_blueprint.route('/psysuitestableupdate.xml')
def psysuitestableupdate():
    print("update request")
    mobile_application = PsysuiteApplication.query.order_by(PsysuiteApplication.id.desc()).first()
    if not mobile_application:
        abort(404)

    stableupdate = mobile_application.stableupdate(request.host_url)

    return Response(response=stableupdate, status=200, mimetype="application/xml")

@admin_blueprint.route('/psysuite.apk')
def psysuite_apk():
    mobile_application = PsysuiteApplication.query.order_by(PsysuiteApplication.id.desc()).first()
    if not mobile_application:
        abort(404)

    return send_file(mobile_application.apk_path, mimetype='application/vnd.android.package-archive')

web/project/user/views.py
from flask import render_template, Blueprint, request, redirect, url_for, flash, abort, jsonify
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, current_user, login_required, logout_user
from threading import Thread
from itsdangerous import URLSafeTimedSerializer
from datetime import datetime
import os
from .forms import LoginForm, EmailForm, PasswordForm, NewPatientForm
from project import db, app
from project.models import User

user_blueprint = Blueprint('user', __name__)


def can_operate_on(user_from, user_to):
    return (user_from.role == User.ADMIN or
            user_from.id == user_to.id or
            user_to.role == User.PATIENT)


def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')


################
#### routes ####
################


@user_blueprint.route('/', methods=['GET'])
@login_required
def index():
    return redirect(current_user.get_homepage())


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                user.authenticated = True
                user.refresh_login()
                db.session.add(user)
                db.session.commit()
                login_user(user)
                flash('Thanks for logging in, {}'.format(current_user.email))
                if user.role == User.ADMIN:
                    redirect_url = url_for('user.view_users')
                else:
                    redirect_url = url_for('user.view_patients')
                return redirect(redirect_url)
            else:
                flash('ERROR! Incorrect login credentials.', 'error')
    return render_template('login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Goodbye!', 'info')
    return redirect(url_for('user.login'))


@user_blueprint.route('/<int:id>/user_profile')
@login_required
def user_profile(id):
    user = User.query.filter(User.id == id).first()
    if not can_operate_on(current_user, user):
        abort(403)
    return render_template('user_profile.html', user=user)


@user_blueprint.route('/<int:id>/email_change', methods=["GET", "POST"])
@login_required
def user_email_change(id):
    user = User.query.filter(User.id == id).first()
    if not can_operate_on(current_user, user):
        abort(403)
    form = EmailForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user_check = User.query.filter_by(email=form.email.data).first()
                if user_check is None:
                    user.email = form.email.data
                    db.session.add(user)
                    db.session.commit()
                    return redirect(url_for('user.user_profile', id=user.id))
                else:
                    flash('Sorry, that email already exists!', 'error')
            except IntegrityError:
                flash('Error! That email already exists!', 'error')
    return render_template('email_change.html', form=form, user=user)


@user_blueprint.route('/<int:id>/password_change', methods=["GET", "POST"])
@login_required
def user_password_change(id):
    user = User.query.filter(User.id == id).first()
    if not can_operate_on(current_user, user):
        abort(403)
    form = PasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            flash('Password has been updated!', 'success')
            return redirect(url_for('user.user_profile', id=user.id))

    return render_template('password_change.html', form=form, user=user)


@user_blueprint.route('/view_patients')
@login_required
def view_patients():
    if current_user.role == User.PATIENT:
        abort(403)
    else:
        users = User.query.filter(
            User.role == User.PATIENT).order_by(User.id).all()
        return render_template('view_patients.html', users=users)


@user_blueprint.route('/view_users')
@login_required
def view_users():
    if current_user.role != User.ADMIN:
        abort(403)
    else:
        users = User.query.order_by(User.id).all()
        return render_template('view_users.html', users=users)


@user_blueprint.route('/new_patient', methods=['GET', 'POST'])
def new_patient():
    form = NewPatientForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(role=User.PATIENT)
                db.session.add(new_user)
                db.session.commit()
                flash('New patient added', 'success')
                return redirect(url_for('user.user_profile', id=new_user.id))
            except IntegrityError:
                db.session.rollback()
                flash('An error happened', 'error')
    return render_template('new_patient.html', form=form)


@user_blueprint.route('/<int:id>/api_key_reset', methods=["GET", "POST"])
@login_required
def api_key_reset(id):
    user = User.query.filter(User.id == id).first()
    if not can_operate_on(current_user, user):
        abort(403)
    if request.method == 'POST':
        try:
            user.regenerate_api_key()
            db.session.add(user)
            db.session.commit()
            flash('api key reset completed with success', 'success')
            return redirect(url_for('user.user_profile', id=user.id))
        except IntegrityError:
            db.session.rollback()
            flash('An error happened', 'error')
    return render_template('api_key_reset.html', user=user)

web/project/templates/_form_macros.html
{% macro render_field(field) %}
  <dt>{{ field.label }}:
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_field_without_label(field) %}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_boolean_field(field) %}
  <dd>{{ field(**kwargs)|safe }} {{ field.label }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}


{% macro render_errors(field) %}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
{% endmacro %}

web/project/templates/admin.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field_without_label %}

{% block content %}

<div>
  <div class="page-header">
    <h2>Admin</h2>
  </div>
  <div>
    <a class="btn btn-sm btn-link" href="{{ url_for('admin.mobile_application_latest') }}">Latest Mobile Application</a>
  </div>
    
  <div>
    <a class="btn btn-sm btn-link" href="{{ url_for('admin.mobile_application_new') }}">New Mobile Application</a>
  </div>

  <div>
    <a class="btn btn-sm btn-link" href="{{ url_for('admin.psysuite_application_latest') }}">Latest PsySuite Application</a>
  </div>

  <div>
    <a class="btn btn-sm btn-link" href="{{ url_for('admin.psysuite_application_new') }}">New PsySuite Application</a>
  </div>
</div>

{% endblock %}

web/project/templates/api_key_reset.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field_without_label %}

{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>Reset api key</h2>
  </div>

  <p>Do you really want to reset the api key for patient {{user.get_username()}}?</p>
  <form action="{{ url_for('user.api_key_reset', id=user.id) }}" method="POST">
    <button class="btn btn-sm btn-success" type="submit">Confirm</button>
    <a class="btn btn-sm bt-default" href="{{current_user.get_homepage()}}">Cancel</a>
  </form>
</div>

{% endblock %}

web/project/templates/email_change.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field_without_label %}

{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>Email Change</h2>
  </div>

  <p>Current Email: {{ user.email }}</p>
  <p>Please enter your new email address:</p>
  <form action="{{ url_for('user.user_email_change', id=user.id) }}" method="POST">
  {{ form.csrf_token }}
    <dl>
      {{ render_field_without_label(form.email, placeholder="Enter New Email Address") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>

{% endblock %}

web/project/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="AllSpeak">
  <meta name="author" content="Federico Bozzini">
  <title>AllSpeak</title>
  <!-- styles -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
    crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>

<body>

  <!-- Static navbar -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">

      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#allspeak-navbar" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">AllSpeak</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="allspeak-navbar">
        <ul class="nav navbar-nav">
          {% if current_user.is_authenticated %} 
            {% if current_user.role == current_user.ADMIN %}
              <li>
                <a href="{{ url_for('admin.admin') }}">Admin</a>
              </li>
            {% endif %}
            {% if current_user.role == current_user.NEUROLOGIST %}
              <li>
                <a href="{{ url_for('user.view_patients') }}">View Patients</a>
              </li>
            {% else %}
              <li>
                <a href="{{ url_for('user.view_users') }}">View Users</a>
              </li>
            {% endif %}
            <li>
              <a href="{{ url_for('user.new_patient') }}">New Patient</a>
            </li>
          {% else %}
            <li>
              <a href="{{ url_for('user.login') }}">Log In</a>
            </li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
          <li>
            <a href="{{ url_for('user.user_profile', id=current_user.id) }}">{{current_user.email}}</a>
          </li>
          <li>
            <div class="navbar-form">
              <div class="btn-group">
                <button type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <a class="btn btn-link" href=" {{ url_for( 'user.logout') }} ">Log Out</a>
                  </li>
                </ul>
              </div>
            </div>
          </li>
          {% else %}
          <li>
            <a href="# ">Welcome!</a>
          </li>
          {% endif %}
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
    <!-- /.container -->
  </nav>

  <div class="container ">
    <div class="content ">

      <!-- flash messages -->
      {% for error_message in get_flashed_messages(category_filter=["error"]) %}
      <div class="alert alert-danger alert-dismissible ">{{ error_message }}</div>
      {% endfor %} {% for success_message in get_flashed_messages(category_filter=["success"]) %}
      <div class="alert alert-success alert-dismissible ">{{ success_message }}</div>
      {% endfor %} {% for info_message in get_flashed_messages(category_filter=["info"]) %}
      <div class="alert alert-info alert-dismissible ">{{ info_message }}</div>
      {% endfor %}

      <!--
        {% for debug_message in get_flashed_messages(category_filter=["debug"]) %}
          <div class="alert alert-info alert-dismissible ">{{ debug_message }}</div>
        {% endfor %}
-->
      <!-- child template -->
      {% block content %} {% endblock %}

    </div>
    <div class="footer ">
      <hr>
      <p>AllSpeak - 2018</p>
    </div>
  </div>
  <!-- /.container -->

  <!-- scripts -->
  <script src="//code.jquery.com/jquery-1.11.3.min.js "></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js " integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS "
    crossorigin="anonymous "></script>
</body>

</html>

web/project/templates/login.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-registration">
  <div class="page-header">
    <h2>Log In</h2>
  </div>
  <form action="{{ url_for('user.login') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Email address") }}
      {{ render_field(form.password, placeholder="Password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Log In</button>
  </form>
</div>

{% endblock %}

web/project/templates/mobile_application_new.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div>
  <div class="page-header">
    <h2>New Mobile Application</h2>
  </div>
  <form action="{{ url_for('admin.mobile_application_new') }}" method="POST" enctype="multipart/form-data">
  {{ form.csrf_token }}
    <dl>
      {{ render_field(form.version, placeholder="Version Code") }}
      {{ render_field(form.sver, placeholder="Version String") }}
      {{ render_field(form.description, placeholder="Description") }}
      {{ render_field(form.apk) }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Create</button>
  </form>
</div>

{% endblock %}

web/project/templates/new_patient.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field_without_label %}

{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>New Patient</h2>
  </div>

  <p>Do you really want to insert a new patient?</p>
  <form action="{{ url_for('user.new_patient') }}" method="POST">
  {{ form.csrf_token }}
    <dl>
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Confirm</button>
    <a class="btn btn-sm bt-default" href="{{current_user.get_homepage()}}">Cancel</a>
  </form>
</div>

{% endblock %}

web/project/templates/password_change.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>Password Change</h2>
  </div>

  <form action="{{ url_for('user.user_password_change', id=user.id) }}" method="POST">
  {{ form.csrf_token }}
    <dl>
      {{ render_field(form.password, placeholder="Enter New Password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>

{% endblock %}

web/project/templates/psysuite_application_detail.html
{% extends "layout.html" %} {% from "_form_macros.html" import render_field %} {% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>PsySuite Application</h2>
  </div>

  <div class="row">
    <div class="col-sm-6">
      {% if mobile_application %}
        <div class="panel panel-primary">
          <div class="panel-heading">Details</div>
          <div class="panel-body">
            Version Code: {{mobile_application.version}}
          </div>
          <div class="panel-body">
            Version String: {{mobile_application.sver}}
          </div>
          <div class="panel-body">
            Description: {{mobile_application.description}}
          </div>
        </div>
      {% else %}
        No PsySuite Application uploaded
      {% endif %}
  </div>
</div>

{% endblock %}

web/project/templates/psysuite_application_new.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div>
  <div class="page-header">
    <h2>New PsySuite Application</h2>
  </div>
  <form action="{{ url_for('admin.psysuite_application_new') }}" method="POST" enctype="multipart/form-data">
  {{ form.csrf_token }}
    <dl>
      {{ render_field(form.version, placeholder="Version Code") }}
      {{ render_field(form.sver, placeholder="Version String") }}
      {{ render_field(form.description, placeholder="Description") }}
      {{ render_field(form.apk) }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Create</button>
  </form>
</div>

{% endblock %}

web/project/templates/user_profile.html
{% extends "layout.html" %} {% from "_form_macros.html" import render_field %} {% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>User Profile</h2>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading">Username</div>
        <div class="panel-body">
          {{user.get_username()}}
        </div>
      </div>

      <div class="panel panel-info">
        <div class="panel-heading">Account Actions</div>
        {% if user.role != user.PATIENT %}
        <div class="panel-body">
          <a href="{{ url_for('user.user_email_change', id=user.id) }}">Change Email Address</a>
        </div>
        {% endif %} {% if user.role != user.PATIENT %}
        <div class="panel-body">
          <a href="{{ url_for('user.user_password_change', id=user.id) }}">Change Password</a>
        </div>
        {% endif %}
        <div class="panel-body">
          <a href="{{ url_for('user.api_key_reset', id=user.id) }}">Reset api-key</a>
        </div>
      </div>

      <div class="panel panel-info">
        <div class="panel-heading">Info</div>
        <div class="panel-body">api-key: {{user.api_key}}</div>
        <div class="panel-body">Inserted on: {{ user.registered_on | datetime }}</div>
        <div class="panel-body">Last login: {{ user.current_logged_in | datetime }}</div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

web/project/templates/view_patients.html
{% extends "layout.html" %}

{% block content %}

<div class="admin-view-users">
  <div class="page-header">
    <h2>Patients</h2>
  </div>

  <div class="row">
    <table class="table table-striped" id="admin_list_of_users">
      <thead>
        <tr>
          <th>Username</th>
          <th>api-key</th>
          <th>Registration Date</th>
          <th>Last login</th>
          </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td><a href="{{ url_for('user.user_profile', id=user.id) }}"> {{ user.get_username() }} </a></td>
            <td> {{ user.api_key }} </td>
            <td> {{ user.registered_on | datetime }} </td>
            <td> {{ user.current_logged_in | datetime }} </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

web/project/templates/view_users.html
{% extends "layout.html" %}

{% block content %}

<div class="admin-view-users">
  <div class="page-header">
    <h2>Patients</h2>
  </div>

  <div class="row">
    <table class="table table-striped" id="admin_list_of_users">
      <thead>
        <tr>
          <th>Username</th>
          <th>Role</th>
          <th>api-key</th>
          <th>Registration Date</th>
          <th>Last login</th>
          </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td><a href="{{ url_for('user.user_profile', id=user.id) }}"> {{ user.get_username() }} </a></td>
            <td> {{ user.role }} </td>
            <td> {{ user.api_key }} </td>
            <td> {{ user.registered_on | datetime }} </td>
            <td> {{ user.current_logged_in | datetime }} </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}